package com.tecnostore;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

final class Database {
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private Database() {
    }

    static void initialize() {
        try {
            Class.forName("org.h2.Driver");
            Files.createDirectories(Path.of("..", "base-de-datos", "data"));
            try (Connection connection = getConnection()) {
                createSchema(connection);
                seedUsers(connection);
                seedProducts(connection);
            }
        } catch (Exception exception) {
            throw new IllegalStateException("No se pudo inicializar la base de datos", exception);
        }
    }

    static Connection getConnection() throws SQLException {
        Path dbPath = Path.of("..", "base-de-datos", "data", "tecnostore").toAbsolutePath().normalize();
        String normalizedPath = dbPath.toString().replace("\\", "/");
        String url = "jdbc:h2:file:" + normalizedPath + ";MODE=MySQL;DATABASE_TO_UPPER=false";
        return DriverManager.getConnection(url, USER, PASSWORD);
    }

    private static void createSchema(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name VARCHAR(120) NOT NULL,
                        email VARCHAR(150) NOT NULL UNIQUE,
                        password VARCHAR(120) NOT NULL,
                        role VARCHAR(20) NOT NULL DEFAULT 'usuario',
                        phone VARCHAR(30),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(140) NOT NULL,
                        description VARCHAR(500) NOT NULL,
                        category VARCHAR(80) NOT NULL,
                        price DECIMAL(12, 2) NOT NULL,
                        stock INT NOT NULL DEFAULT 0,
                        image_url VARCHAR(250),
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS sales_orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_number VARCHAR(40) NOT NULL UNIQUE,
                        user_id BIGINT NOT NULL,
                        customer_name VARCHAR(120) NOT NULL,
                        customer_email VARCHAR(150) NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        subtotal DECIMAL(12, 2) NOT NULL,
                        shipping DECIMAL(12, 2) NOT NULL,
                        total DECIMAL(12, 2) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS order_items (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id BIGINT NOT NULL,
                        product_id BIGINT NOT NULL,
                        product_name VARCHAR(140) NOT NULL,
                        unit_price DECIMAL(12, 2) NOT NULL,
                        quantity INT NOT NULL,
                        subtotal DECIMAL(12, 2) NOT NULL,
                        CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
                        CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(id)
                    )
                    """);
        }
    }

    private static void seedUsers(Connection connection) throws SQLException {
        if (count(connection, "users") > 0) {
            return;
        }
        try (PreparedStatement statement = connection.prepareStatement("""
                INSERT INTO users (full_name, email, password, role, phone)
                VALUES (?, ?, ?, ?, ?)
                """)) {
            insertUser(statement, "Administrador", "admin@gmail.com", "admin", "admin", "+51 999 888 777");
            insertUser(statement, "Usuario Demo", "usuario@gmail.com", "usuario", "usuario", "+51 988 777 666");
        }
    }

    private static void insertUser(
            PreparedStatement statement,
            String fullName,
            String email,
            String password,
            String role,
            String phone
    ) throws SQLException {
        statement.setString(1, fullName);
        statement.setString(2, email);
        statement.setString(3, password);
        statement.setString(4, role);
        statement.setString(5, phone);
        statement.executeUpdate();
    }

    private static void seedProducts(Connection connection) throws SQLException {
        if (count(connection, "products") > 0) {
            return;
        }
        ProductInput[] products = new ProductInput[] {
                new ProductInput("iPhone 15 Pro", "Smartphone premium con chip A17 Pro y camara profesional.", "Smartphone", new BigDecimal("1199.00"), 18, "assets/img/iphone15.png"),
                new ProductInput("MacBook Pro M3", "Laptop profesional para desarrollo, diseno y productividad.", "Laptop", new BigDecimal("2299.00"), 10, "assets/img/laptop.png"),
                new ProductInput("iPad Air", "Tablet ligera para estudiar, trabajar y entretenimiento.", "Tablet", new BigDecimal("699.00"), 20, "assets/img/ipadair.png"),
                new ProductInput("AirPods Pro", "Audifonos inalambricos con cancelacion activa de ruido.", "Audio", new BigDecimal("249.00"), 35, "assets/img/airpodspro.png"),
                new ProductInput("Samsung Galaxy S24", "Smartphone Android con pantalla AMOLED y camara avanzada.", "Smartphone", new BigDecimal("999.00"), 16, "assets/img/galaxys24.png"),
                new ProductInput("Dell XPS 13", "Ultrabook premium con pantalla compacta de alta resolucion.", "Laptop", new BigDecimal("1299.00"), 12, "assets/img/dellxps13.png"),
                new ProductInput("Nintendo Switch", "Consola hibrida para jugar en casa o en modo portatil.", "Gaming", new BigDecimal("349.00"), 25, "assets/img/nintendoswitch.png"),
                new ProductInput("Apple Watch Series 9", "Reloj inteligente con GPS y monitoreo de salud.", "Wearable", new BigDecimal("429.00"), 22, "assets/img/applewatchseries9.png"),
                new ProductInput("Sony WH-1000XM5", "Audifonos over-ear con cancelacion de ruido lider.", "Audio", new BigDecimal("399.00"), 15, "assets/img/sonywh1000xm5.png"),
                new ProductInput("LG OLED 65", "Smart TV OLED 4K con HDR, Dolby Vision y webOS.", "TV", new BigDecimal("1899.00"), 8, "assets/img/lgoled65.png"),
                new ProductInput("Canon EOS R6", "Camara mirrorless profesional con grabacion 4K.", "Camara", new BigDecimal("2499.00"), 7, "assets/img/canoneosr6.png"),
                new ProductInput("Razer DeathAdder V3", "Mouse gaming ergonomico con sensor de alta precision.", "Gaming", new BigDecimal("89.00"), 40, "assets/img/razerdeathadderv3.png")
        };

        ProductRepository repository = new ProductRepository();
        for (ProductInput product : products) {
            repository.create(product);
        }
    }

    private static int count(Connection connection, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             var resultSet = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }
}
